Document: cue2pops
Title: Debian cue2pops Manual
Author: <insert document author here>
Abstract: This manual describes what cue2pops is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cue2pops/cue2pops.sgml.gz

Format: postscript
Files: /usr/share/doc/cue2pops/cue2pops.ps.gz

Format: text
Files: /usr/share/doc/cue2pops/cue2pops.text.gz

Format: HTML
Index: /usr/share/doc/cue2pops/html/index.html
Files: /usr/share/doc/cue2pops/html/*.html
